keys:
  - &machine_zenith age1ep7mt0ztyx54nf25sjfx3tutxvx22ddsvczkevvyv2erm5u0ufkqhgt4lv
  - &machine_nadir age17yt5e6jx9vxpsdq798x2uljdnqzqlhzlhza24kl45hzarayfk3jspzuc9v
creation_rules:
  - path_regex: users/adophilus/secrets/env
    age:
    - *machine_zenith
    - *machine_nadir
  - path_regex: users/adophilus/secrets/wg0-private-key
    age:
    - *machine_zenith
  - path_regex: users/adophilus/secrets/wg-nadir-key
    age:
    - *machine_zenith
    - *machine_nadir
