# Optimized for: Arch Linux | Hyprland | UWSM
# -------------------------------------------------------------------------------------------------

# --- SYSTEM ESSENTIALS ---

# Gnome Keyring: Stores passwords for apps (VSCode, Chrome, etc.). (recommanded to enable systemd service instead of auto starting with exec-once)
exec-once = uwsm-app -- gnome-keyring-daemon --start --components=secrets
# OR
# replace the exec-once line with:
# exec-once = uwsm-app -- systemctl --user start gnome-keyring-daemon.service

# XHost: Grants root access to the display (needed for GParted/Synaptic to run).
# exec-once = uwsm-app -- xhost +si:localuser:root



# --- BACKGROUND SERVICES ---
exec-once = uwsm-app -- swww-daemon              # Wallpaper engine (used by Quickshell)
exec-once = uwsm-app -- playerctld               # Media player daemon (Mpris)
exec-once = ~/user_scripts/waybar/network/network_meter_daemon.sh

# hypridle has systemd service
# exec-once = uwsm-app -- hypridle              # Idle manager
# exec-once = uwsm-app -- swayosd-server        # OSD for Volume/Brightness


# --- CLIPBOARD MANAGER ---
exec-once = uwsm-app -- wl-paste --type text --watch cliphist store
exec-once = uwsm-app -- wl-paste --type image --watch cliphist store

# --- QUICKSHELL DESKTOP SHELL ---
exec-once = ~/.config/hypr/scripts/settings_watcher.sh &
exec-once = ~/.config/hypr/scripts/volume_listener.sh
exec-once = quickshell -p ~/.config/hypr/scripts/quickshell/Shell.qml

# --- OPTIONAL / USER INTERFACE ---
# exec-once = uwsm-app -- waybar               # Replaced by Quickshell's TopBar
# exec-once = uwsm-app -- hyprpaper             # Replaced by swww


# --- Slow app launch fix -- set systemd vars
exec-once = systemctl --user import-environment $(env | cut -d'=' -f 1)
exec-once = dbus-update-activation-environment --systemd --all
